### ISSUE TITLE
中文版汉化问题

### ISSUE THREAD

**Issue by Sirius-L** [mmusu3/SEToolbox#4]
程序内所有的文本都变成了“实验test” 完全无法正常使用
![QQ截图20241016194124](https://github.com/user-attachments/assets/828b9787-c9aa-4a6f-9023-1d4337edd196)

**Comment by mmusu3** [comment]
It seems that the Chinese translation file is mostly empty apart from a couple of items and the rest is just filled with this 'test' text. I only have enough time to keep SE Toolbox working between game versions and so will not be able to add a proper translation. All I can do is remove the test items which will allow them to fallback to English text. For now though as a workaround you can change the language setting to English using the '?' button in the top right.

**Comment by mmusu3** [comment]
Resolved by fa35cfd78ac0d4eabedee1d63ede7e7e928c9f67
