### ISSUE TITLE
Trying to repair a SE dedicated server save kills SEToolbox

### ISSUE THREAD

**Issue by risingfish** [mmusu3/SEToolbox#5]
- [X] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [X] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [ ] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 01.205.023.1
**SE Version:** 1.205.023 b1

### SEToolbox crashed
What were you doing with SEToolbox when it happened? Trying to repair a saved game. The saved game is one that we've been playing for a few weeks. We installed some new mods a week ago, and I think that one of them corrupted the saved game somehow. I removed all the mods we added during the past week, and things have improved, but we're seeing connection issues. I download SEToolbox to try to repair the save, but our save appears to break SEToolbox. Sorry. Here's a screen shot of the error:

![SEToolboxError](https://github.com/user-attachments/assets/b1ade03f-2edd-48fe-89d6-99e5b05297d9)

I would be happy to provide the save if it would be helpful, but it's a 236 MB file, so we'd need to figure out how to get it to you.

### Steps to Reproduce
1. How did this issue get triggered?
- This was triggered by trying to repair a broken Saved game.

2. Write all of the steps here.
- Launched SEToolbox and tried repairing the file.

### SEToolbox Event Log
```
Fault bucket 1847293574927131546, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: SEToolbox.exe
P2: 1.205.23.1
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\zac\AppData\Local\Temp\RDR2477.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2487.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER24C7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER24F4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2514.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 6b1b3a34-732d-44b1-82f5-7f5a018eb9d0
Report Status: 268435456
Hashed bucket: b91564535a411a7cb9a2e7b81164a39a
Cab Guid: 0
```

**Comment by mmusu3** [comment]
Hi, sorry about the outdated issue template. I'll get that fixed. As for your problem, the event log info you have there isn't very helpful unfortunately. Providing the save file would be the best option. Is that save size uncompressed? If so what is the size after putting the files in a zip archive.

**Comment by risingfish** [comment]
Yeah, I didn't think that event info will help but thought I'd included. I'll keep trying to get the event to show up properly in the Event Viewer. Yeah, the size seems a little crazy. That 230MB is the entire zip archive I created with 7 zip, but the bulk of the size come the Earthlike vx2 file. It's 222MB by itself: 

![image](https://github.com/user-attachments/assets/35ac376d-e3ca-4d25-9cfb-9a131566531b)

I do run a personal nextcloud server I can put the zip on so you can get it, I just don't want to put the URL here in github for all to see. I'm always paranoid I missed some security setting on the webserver and try not to expose it too much. :)

**Comment by risingfish** [comment]
I forgot to mention that while I can't repair, I can open the save, edit it, and save it. So that bit works.

**Comment by mmusu3** [comment]
If you have Discord and are on the KeenSWH server you can search for my profile (`@Remaarn`) and send me a private message.

**Comment by mmusu3** [comment]
I found a potential cause for the issue. I will release a new version tomorrow and you can test it on your world to see if the problem is gone.

**Comment by risingfish** [comment]
Great! I'll be ready to test when you are.

**Comment by mmusu3** [comment]
I've published a new version give it a try.

**Comment by risingfish** [comment]
We're in business, that error is gone. Now just need to figure how to get the game to recognized the earthlike planet file again. Thank you for being so quick with the fix!
