### ISSUE TITLE
Error while trying to install SEToolbox

### ISSUE THREAD

**Issue by Imicus** [mmusu3/SEToolbox#6]
- [x] Ensure you are using the latest version of SEToolbox. You can get it from [here.](https://github.com/mmusu3/SEToolbox/releases/latest)
- [x] Ensure that the issue is reproducible, that you can make it occur more than once.
- [ ] If the issue involves a world / blueprint, please provide the relevant files if possible.
- [ ] In the case of a crash find the log.txt file in the application folder.

Please provide the relevant version numbers.  
**SEToolbox Version:** `1.205.024.1`  
**SE Version:** `1.205.024 b2`

### Issue Description
What is the issue and what were you doing with SEToolbox when it occurred?
I recieved this error while trying to install SEToolbox.
![SEtoolbox error](https://github.com/user-attachments/assets/7a72130b-0f06-4952-8d5a-9c85fa23557c)

### Steps to Reproduce
1. How did this issue get triggered?
Installing SEToolbox
2. Write all of the steps here.
Install SEToolbox
### SEToolbox Log File
```
No log file
```

**Comment by mmusu3** [comment]
Hi, there isn't much for me to go with here. By 'installing SEToolbox' are you referring to this prompt that shows when first running the application after extracting the files from the downloaded zip?

![image](https://github.com/user-attachments/assets/18d004fe-4d19-4036-bd07-c72fb04b76f7)

My releases of SE Toolbox don't include an installer like the old ones so I want to be clear on what you mean, thanks!

**Comment by Imicus** [comment]
Hey, thanks for replying, sorry for not giving much to go on. I meant running SEToolbox from the folder after extracting it.
I get the prompt you posted, followed by this;
![SEtoolbox error 2](https://github.com/user-attachments/assets/4bafa31c-3276-412d-84aa-d39adfbbea8d)
So I click ok and then error box from my first post appears.

**Comment by mmusu3** [comment]
I have made a new test version that should give better information about what is going wrong. If you encounter the message box shown in your post again, click 'No' this time and then share the contents of the 'updater-log.txt' file that should appear.
The test version is not in the releases section, I have linked it here:
[SEToolbox-test.zip](https://github.com/user-attachments/files/17502828/SEToolbox-test.zip)

**Comment by Imicus** [comment]
I have downloaded the test version and clicked 'No' as instructed but no 'updater-log.txt' file appears. I have also tried clicking 'Yes', and tried running as administrator, but still no file. No 'updater-log.txt' file appears for the normal version either.
![SEtoolbox error 3](https://github.com/user-attachments/assets/d90050f6-bf2e-467b-a7cf-484d9c4c2eaf)

**Comment by mmusu3** [comment]
I am having a hard time understanding why the log file would not be showing up for you. I have made a new test version that should also output two more files (`trace.txt` and `trace-elevated.txt`) as a last attempt to diagnose the issue. Please give it a try.
[SEToolbox-test.zip](https://github.com/user-attachments/files/17516977/SEToolbox-test.zip)

**Comment by Imicus** [comment]
I have tried the new test version, but this time it just flashes the SEToolbox logo and then closes immediately. No output of the files you mentioned.

**Comment by mmusu3** [comment]
I'm sorry I don't know what else to try. My assumption is that you have some sort of file permissions issue wherever you are extracting the SEToolbox zip to. After the logo shows and goes away, check the windows event log to see if there is anything there, otherwise I cannot help you further.

**Comment by mmusu3** [comment]
I am closing this issue. If you manage to get any further information please share it here, thanks.

**Comment by simon-b** [comment]
I saw SEToolbox immediately exit after splashing logo, with no error and no log produced.
I noticed that the SEToolbox folder, extracted from the zip distributed as a release, is `read only` by default.

Changing this folder permission solves this issue.
