### ISSUE TITLE
Error while parsing config file

### ISSUE THREAD

**Issue by Zemogiter** [mmusu3/SEToolbox#8]
- [x] Ensure you are using the latest version of SEToolbox. You can get it from [here.](https://github.com/mmusu3/SEToolbox/releases/latest)
- [x] Ensure that the issue is reproducible, that you can make it occur more than once.
- [ ] If the issue involves a world / blueprint, please provide the relevant files if possible.
- [ ] In the case of a crash find the log.txt file in the application folder.

Please provide the relevant version numbers.  
**SEToolbox Version:** `SEToolbox-1.205.026.1`  
**SE Version:** `1.205.026 b0 default`

### Issue Description
Uppon launching the toolbox's exe file I get an "error while parsing configuration file" message.

### Steps to Reproduce
1. Unpack the latest SEToolbox zipfile to `C:\Portable Programs\SEToolbox` (also tried the Downloads folder, same thing happens)
2. Launch `SEToolbox.exe`

### SEToolbox Log File
The log file is empty.

**Comment by mmusu3** [comment]
I am not able tell what is wrong from just your description. Can you provide a screenshot of the error message.

**Comment by Zemogiter** [comment]
![Image](https://github.com/user-attachments/assets/bfb01c8a-c280-4d6c-a262-1c8a9bb0dfbf)
This is the error I've been getting.

**Comment by mmusu3** [comment]
This error is not coming directly from SEToolbox. As far as I can tell is it a problem with something else on your system, perhaps your installation of .NET Framework or Visual C++ Runtime. There seem to be a small handful of reports across the web of that same error that appearing in other software.
All I can do is ask you to make sure your system is up to date and working correctly. There is nothing else I can do about this, I really don't have the time needed to help you debug this further, sorry.
